export class ListPages {
  static readonly Main = 'Main'
  static readonly AboutProject = 'AboutProject'
  static readonly AboutLaboratory = 'AboutLaboratory'
  static readonly ListNotification = 'ListNotification'
  static readonly SearchProduct = 'SearchProduct'
  static readonly Research = 'Research'
  static readonly Tastings = 'Tastings'
  static readonly SearchManufacturer = 'SearchManufacturer'
  static readonly ScanProduct = 'ScanProduct'
  static readonly BarcodeSearchResults = 'BarcodeSearchResults'
  static readonly ResultResearch = 'ResultResearch'
  static readonly ScannedProduct = 'ScannedProduct'
  static readonly LocalResearch = 'LocalResearch'
  static readonly Help = 'Help'
}
