export enum Color {
    white = '#FFFFFF',
    silverSand = "#C2C2C2",
    fauxAntiFlashWhite = "#edf1f8",
    pigment = "#EC1C23",
    chineseBlack = "#161616",
    eerieBlack = "#1A1A1A",
    aliceBlue = "#DDEFFB",
    manatee = "#969ca1",
    spanishBlue = "#0065BB",
    green = "#00ad6f",
    palePink = "#FFD5D6",
    azureishWhite = "#dfeffc",
    ashGray = "#B4B8BB",
    gray = "#BEBEBE",
    black = "black",
    cyanCornflowerBlue = "#2980B9",
}